### 권한 다시 받기

> git에 push를 했는데 403error가 발생하면서 권한이 없다고 뜰 때 사용

```python
git remote set-url origin "https://{github-username}@github.com/{github-username}/{github-repository-name}.git"
```

